sudo: required
services:
  - docker

before_install:
  - docker build -t akash/react-test -f ./client/Dockerfile.dev ./client
  

script:
  - docker run akash/react-test npm test -- --coverage
after_success:
  - docker build -t akash/multi-client ./client
  - docker build -t akash/multi-nginx ./nginx
  - docker build -t akash/multi-server ./server
  - docker build -t akash/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push akash/multi-client 
  - docker push akash/multi-nginx
  - docker push akash/multi-service
  - docker push akash/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app: test
  env: Test-env-1
  bucket_name: elasticbeanstalk-ap-south-1-243020057751
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
  
 

    
