sudo: required
services:
  - docker

before_install:
  - docker build -t akash/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run akash/react-test npm test -- --coverage
after_success:
 - docker build -t akasht/akash:multi-client ./client
 - docker build -t akasht/akash:multi-nginx ./nginx
 - docker build -t akasht/akash:multi-server ./server
 - docker build -t akasht/akash:multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push akasht/multi-client
  - docker push akasht/multi-nginx
  - docker push akasht/multi-service
  - docker push akasht/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app:  multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-243020057751
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



